before_install:
  - gem install sass

install:
  - npm install

script:
  - npm run test
  - npm run build

deploy:
  provider: npm
  email: maartenpaauw@gmail.com
  skip_cleanup: true
  api_key:
    secure: ydNgeBnhJlYd+/upEz2XqHXrG9JXcsn3ND3ccDvLRhRVUVwmZmiDAllHG88f5qi3YwWpze+zR86otiwKuly/olXde1OrzZnfZkCmooUaMy6M5wn7xZiM8hkp8axFzBsKTknskhhxDOPPP4no/4mHsy0JY4FuQBv+BJf8hE3UB3rL7VVZAaaUgFL8N+MqEE2AH5csfoZM6eNhWWC9sMWumFIx+n9nQviZ5nF55pJyzDbhyCpKs9SZCB98a/EbfmLeByV7K2aVxqhKblp0TxMRwzAd3cjuUDo1st7hPUmLT0eC38DAGBheYXtDjEI3kNv8bkyJk53iyQVoLW9KAL8u4duTB23zoTyKysJGTtaizIBv/CvtCzuG9qEBo34yldbUHN4EMrJ/57jxrGxbw+6d9mDpStcB7FWRpeYN37hacyRKToEuEt33xicVin4bCAvMAiyFkOqXNNZ4ewWjjEqtv32M/FLITD1BhC8t3g1KSdei61pfNxXW37CZx+BQo+cmyutw4dB9i090xL48aNmFpDk6Oo02FzhXGAViRlSaPFecTrPWt3j5ubDz2Q5jt5+UUubGt2CQaw8aeEw+cgZwIYXDzYqYmdHXnS4W3D7vWMCAcv1MUaHs4UMFkkpRVbFZnnVzgN1cFqas/5IDrDS6Asr27JrdaVjcyZkz0PsNwTI=
  on:
    tags: true
    branch: master
    repo: maartenpaauw/flat-ui-colors-helper
